{
 "title": "Sensors metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource" }
  ]
 },
 "panels": [
  {
   "title": "AVG Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_temperature_sensors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AVG Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_humidity_sensors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature Inside",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "temperature_Sensor1", "legendFormat": "Sensor 1" },
    { "expr": "temperature_Sensor2", "legendFormat": "Sensor 2" }
   ]
  },
  {
   "title": "Humidity Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "humidity_Sensor1", "legendFormat": "Sensor 1" },
    { "expr": "humidity_Sensor2", "legendFormat": "Sensor 2" }
   ]
  }
 ]
}