groups:
  - name: average_humidity_rules
    rules:
      - record: avg_humidity_sensors
        expr: (humidity_Sensor1 + humidity_Sensor2) / 2
        labels:
          job: "sensor_aggregation"
      - record: avg_temperature_sensors
        expr: (temperature_Sensor1 + temperature_Sensor2) / 2
        labels:
          job: "sensor_aggregation"
