groups:
  - name: average_humidity_rules
    rules:
      - record: avg_humidity_sensors
        expr: avg(humidity_Sensor1, humidity_Sensor2)
        labels:
          job: "sensor_aggregation"
      - record: avg_temperature_sensors
        expr: avg(temperature_Sensor1, temperature_Sensor2)
        labels:
          job: "sensor_aggregation"
