groups:
  - name: average_humidity_rules
    rules:
      - record: avg_humidity_sensors
        expr: avg(humidity_inside)
        labels:
          job: "sensor_aggregation"
      - record: avg_temperature_sensors
        expr: avg(temperature_inside)
        labels:
          job: "sensor_aggregation"
