groups:
  - name: system-alerts
    rules:
      - alert: HighCPUUsage
        expr: node_cpu_seconds_total{mode="idle"} < 20
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for the last 2 minutes."
  - name: equipment_alerts
    rules:
      - alert: SensorFailure
        expr: absent(temperature_Sensor1) or absent(temperature_Sensor2)
        for: 2m
        labels:
          severity: critical
          equipment: temperature-sensors
        annotations:
          summary: "Sensor data missing"
          description: "Temperature sensor is not reporting data."
  - name: fan_alerts
    rules:
      - alert: HighTemperature
        expr: avg_temperature_sensors > 20
        for: 0s
        labels:
          severity: critical
          equipment: fun
          purpose: fun-control
        annotations:
          summary: "The temperature so high!"
          description: "The avg temperature for the last 5 minutes more than 20 degres"

