global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'python_exporter'
    static_configs:
      - targets: ['127.0.0.1:8000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
