global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'sensor_exporter'
    static_configs:
      - targets: ['host.docker.internal:8000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
