global:
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'sensor_exporter'
    static_configs:
      - targets: ['host.docker.internal:8000']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

rule_files:
  - "/etc/prometheus/additional_sensor_parameters.yml"
  - "/etc/prometheus/alert.rules.yml"
